name: ${project.name}
description: ${project.description}
main: org.retromc.templateplugin.TemplatePlugin
version: ${project.version}
authors:
  - JohnyMuffin
softdepend:
  - Essentials

commands:
  testcommand:
    description: A test command for the plugin.
    usage: /<command> [args]
    aliases: [tc]
    permission: myplugin.testcommand
    permission-message: You do not have permission to use this command.

permissions:
  myplugin.*:
    description: Gives access to all myplugin commands.
    children:
      myplugin.testcommand: true